import Head from 'next/head';
import styles from '../../styles/Layout.module.css';

const Layout = ({ children }) => (
  <>
    <Head>
      <title>Next App Testing</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className={styles.container}>
      <main className={styles.main}>
        {children}
      </main>
    </div>
  </>
);

export default Layout;
